feat: add type annotations for internal code
carlkidcrypto/ezsnmp pull request #149
Opened 2024-08-03 04:10 UTC by wangxin688

continue to add more type annotations for internal code.

@carlkidcrypto I have some questions with un-certain typing.

1. `SNMPVariable` object: I check the entire codebase and pytest(exclude cpp code). why `oid` can be `None`?
2. `snmp_type` is Enum or Literal string, right? which can be found in netsnmp
3. something in `compat.py` seems duplicated. I don't known if that is for python2 (unicode?)

Since a lot of values are set as default value. I was confused if that is the right type annotations.
Also, I fixed some pytest code for null value checking assert.

Please make a double check. thanks

2024-08-03 08:23 UTC, wangxin688 commented
Another thing I want to check is if `SNMPVariable.value` could be `None`(not empty string '')? if that is true, I need check the null value everywhere

2024-08-05 14:47 UTC, wangxin688 commented
anything should I do for CI failing item? I don't known comment-valgrind is and how to fix.

2024-08-05 14:58 UTC, carlkidcrypto commented
> anything should I do for CI failing item? I don't known comment-valgrind is and how to fix.

No, it is failing because not all UTs are passing. It's the same timeout issue from the last PR.

2024-08-05 17:09 UTC, carlkidcrypto commented
> continue to add more type annotations for internal code.
> 
> @carlkidcrypto I have some questions with un-certain typing.
> 
> 1. `SNMPVariable` object: I check the entire codebase and pytest(exclude cpp code). why `oid` can be `None`?
> 2. `snmp_type` is Enum or Literal string, right? which can be found in netsnmp
> 3. something in `compat.py` seems duplicated. I don't known if that is for python2 (unicode?)
> 
> Since a lot of values are set as default value. I was confused if that is the right type annotations.
> Also, I fixed some pytest code for null value checking assert.
> 
> Please make a double check. thanks

For #3, the compat file was for python2. I think we have reached a point where we can remove that file. We ATM only support python3.8 and greater. I'll say, remove it and fix anything that breaks. Odds are we just need to move to python3 "ways" of doing things.

For #2, if I recall `snmp_type` is an integer. It maps to the version: https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/session.py#L181

2024-08-06 02:21 UTC, wangxin688 commented
> > continue to add more type annotations for internal code.
> > @carlkidcrypto I have some questions with un-certain typing.
> > 
> > 1. `SNMPVariable` object: I check the entire codebase and pytest(exclude cpp code). why `oid` can be `None`?
> > 2. `snmp_type` is Enum or Literal string, right? which can be found in netsnmp
> > 3. something in `compat.py` seems duplicated. I don't known if that is for python2 (unicode?)
> > 
> > Since a lot of values are set as default value. I was confused if that is the right type annotations.
> > Also, I fixed some pytest code for null value checking assert.
> > Please make a double check. thanks
> 
> For Q3, the compat file was for python2. I think we have reached a point where we can remove that file. We ATM only support python3.8 and greater. I'll say, remove it and fix anything that breaks. Odds are we just need to move to python3 "ways" of doing things.
> 
> For Q2, if I recall `snmp_type` is a string. It is mapped here from string types to int types : https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/interface.cpp#L327

good to know that python2 coding will be removed. thanks for elaborating questions

2024-08-06 13:57 UTC, carlkidcrypto commented
> continue to add more type annotations for internal code.
> 
> @carlkidcrypto I have some questions with un-certain typing.
> 
> 1. `SNMPVariable` object: I check the entire codebase and pytest(exclude cpp code). why `oid` can be `None`?
> 2. `snmp_type` is Enum or Literal string, right? which can be found in netsnmp
> 3. something in `compat.py` seems duplicated. I don't known if that is for python2 (unicode?)
> 
> Since a lot of values are set as default value. I was confused if that is the right type annotations. Also, I fixed some pytest code for null value checking assert.
> 
> Please make a double check. thanks

For Q1, if we encounter an error we return none. As is the case with `netsnmp_get`. https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/interface.cpp#L2285-L2298 The logic is similar for `netsnmp_walk` https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/interface.cpp#L3067-L3095

2024-08-06 13:59 UTC, carlkidcrypto commented
> Another thing I want to check is if `SNMPVariable.value` could be `None`(not empty string '')? As I checked, if we use `snmpwalk` to iterate mib oids it should be return a Non-Null value if no errors happens. if that is true for value can be NULL, I need check the null value everywhere. Sorry for the bothering, I can't understand how C++ code is working.

Yes, `SNMPVariable.value` can be `None` since we initialize it to `None`: https://github.com/carlkidcrypto/ezsnmp/blob/main/ezsnmp/variables.py#L23-L26

2024-08-06 14:16 UTC, carlkidcrypto requested changes

2024-08-06 14:16 UTC, carlkidcrypto commented on ezsnmp/ez.py
> +    **session_kargs: Any,
If I recall right `session_kargs` is of type `dict`. 

```text
One can think of the kwargs as being a dictionary that maps each keyword to the value that we pass alongside it. That is why when we iterate over the kwargs there doesn’t seem to be any order in which they were printed out.
``` 
https://www.geeksforgeeks.org/args-kwargs-python/

2024-08-06 14:16 UTC, carlkidcrypto commented on ezsnmp/helpers.py
> -def normalize_oid(oid, oid_index=None):
Let's change this function signature to 
`normalize_oid(oid="", oid_index="")`. This should make the typing easier. 

Then the function code becomes

```python3
def normalize_oid(oid="", oid_index=""):
    """
    Ensures that the index is set correctly given an OID definition.

    :param oid: the OID to normalize
    :param oid_index: the OID index to normalize
    """

    # Determine the OID index from the OID if not specified
    if oid_index == "" and oid != "":
        first_match = OID_INDEX_RE.match(oid)
        second_match = OID_INDEX_RE2.match(oid)

        if second_match:
            oid, oid_index = second_match.group(1, 2)

        elif first_match:
            oid, oid_index = first_match.group(1, 2)

        elif oid == ".":
            oid = "."
            oid_index = ""

    return oid, oid_index
```

2024-08-06 14:16 UTC, carlkidcrypto commented on tests/test_ez.py
> +    assert res.value and platform.version() in res.value
why were these changes needed here ?

2024-08-22 22:34 UTC, carlkidcrypto commented
@wangxin688  just reaching out since no changes have happened for a couple weeks.

2024-08-26 04:25 UTC, wangxin688 commented
> @wangxin688 just reaching out since no changes have happened for a couple weeks.

yes. for some items I'm not sure if it's correct typed. could you share more context?

2024-08-27 17:40 UTC, carlkidcrypto commented
> > @wangxin688 just reaching out since no changes have happened for a couple weeks.
> 
> yes. for some items I'm not sure if it's correct typed. could you share more context?

I believe I have answered all your questions in previous comments above.
If not, let me know what ones still need answers.

2024-08-27 19:13 UTC, carlkidcrypto commented on tests/test_ez.py
> +    assert res.value and platform.version() in res.value
Reverted in 
defe428

2024-08-27 19:21 UTC, carlkidcrypto commented on ezsnmp/helpers.py
> -def normalize_oid(oid, oid_index=None):
NTD, I attempted this and it would cause too much change.
It'll need to be investigated further.

2024-08-27 19:31 UTC, carlkidcrypto commented on ezsnmp/ez.py
> +    **session_kargs: Any,
Done in 
dd0c9ee

2024-08-27 19:33 UTC, carlkidcrypto commented
@wangxin688 I have addressed some items. Let me know if they work for you.

2024-08-29 10:29 UTC, wangxin688 commented
> @wangxin688 I have addressed some items. Let me know if they work for you.

thanks for updating. it's ok for me now.

2024-08-29 23:56 UTC, merged